baseURL = "https://camhd-analysis.github.io/"
publishDir = "as_published_to_github/"
languageCode = "en-us"
title = "CamHD Video Analysis"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

pygmentsCodeFences = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  #github = "https://github.com/NOAA-OER16-3DReconstruction"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/header_one.jpg"
  recent_posts_number = 10
